In [49]:
import numpy as np 
import pandas as pd 
from pandas import DataFrame
import math 

'''
make the matrix
'''
def matrix(ann_matrix):
    annotask = ann_matrix.values.tolist()
    #column_name = list(ann[2].unique())
    matrix = DataFrame(index =ann_matrix[ann_matrix.columns[1]].unique())
    matrix_id = DataFrame(index =ann_matrix[ann_matrix.columns[1]].unique())
    column_name=[]
    for elelist in annotask:
        for i in range(0,len(matrix.index)):
            if elelist[1] == matrix.index[i]:
                if elelist[2] not in column_name:
                    column_name.append(elelist[2])  # list of column_name + that name 
                    matrix[elelist[2]] =0 # dataframe add a column of zero with the name of elelist[2]
                colname_index = column_name.index(elelist[2]) # get the index of the name in the list of column name 
                matrix.iloc[i,colname_index] +=1 #+1 at that cell 
    matrix.index = range(0,len(matrix))
    return matrix, matrix_id  # each value of matrix <=4 


def total(matrix):
    total = 0
    for i in range(0,len(matrix)): 
        total = total+ sum(matrix.iloc[i])
    return total


'''
## compute p_j
# The value p_j is the proportion of all assignments that were made to the jth category(column).
# sum of p_j = 1.0
'''
def compute_p_j(orimatrix):
    p_j=[]
    sum_each_oricol = orimatrix.sum(axis=0)
    for i in sum_each_oricol:
        #p_j.append(i/(len(orimatrix.index)*4))                  #annotator = 4
        p_j.append(i/(len(orimatrix.index)*2))                   #annotator = 2
    suquare_p_j = [i*i for i in p_j]
    aveP_e = sum(suquare_p_j)
    return aveP_e

'''
## Compute P_i 
# The extent to which raters agree for the i-th subject.
# -- how many rater-rater pairs are in agreement, relative to the num of all possible rater-rater pairs.
'''
def compute_P_i(orimatrix):
    #n = 4                                                       #annotator = 4
    n = 2                                                        #annotator = 2
    P_i = []
    for i in range(0,len(orimatrix)):
        row_list =[]
        for j in range(0,len(orimatrix.columns)):
            row_list.append(orimatrix.iloc[i][j]*orimatrix.iloc[i][j])
        row_sum = sum(row_list)    
        P_i.append((row_sum-n)/(n*(n-1)))
 
    aveP_i = sum(P_i)/len(P_i)
    return aveP_i


'''
## Compute Kraemer's kappa
'''
def Kraemers_kappa(orimatrix,aveP_e,aveP_i):
    N = len(orimatrix)
    #n = 4                                                       #annotator = 4
    n = 2                                                        #annotator = 2
    k_0 = ((aveP_i-aveP_e)/(1-aveP_e))+((1-aveP_i)/(N*n*(1-aveP_e)))
    return k_0


'''
## Compute Fleiss' kappa
'''
def Fleiss_kappa(orimatrix,aveP_e,aveP_i):
    #n = 4                                                       #annotator = 4
    n = 2                                                        #annotator = 2
    k_1 = (aveP_i-aveP_e)/(1-aveP_e)
    return k_1


'''
## split the matrix as dfs 
# where each id is a df, 
# where each error type is a 
# where each column is two, select(y) or non_select(n)
'''
def split_matrix(matrix):
    F_kappa =[]
    t_matrix = matrix.T
    for i in range(0,len(matrix)):
#        print('SQL hypothesis', i)
        i = t_matrix.columns[i] # sql id
        df = pd.DataFrame(columns = ['selected', 'not_selected'], index =list(matrix.columns))
        df['selected'] = 0
        df['selected'] = t_matrix.iloc[:,i:i+1]
        #df['non_selected'] = 4 - df['selected']                 #annotator = 4
        df['not_selected'] = 2 - df['selected']                  #annotator = 2
        aveP_e = compute_p_j(df)
        aveP_i = compute_P_i(df)
        F_k = Fleiss_kappa(df,aveP_e,aveP_i)
        F_kappa.append(F_k)
#        print(df)
    return F_kappa

---

In [40]:
import os
for dirname, _, filenames in os.walk('/Users/tianyisun/Desktop/NLQbatches/batch123'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/Users/tianyisun/Desktop/NLQbatches/batch123/correct_batch1_anntask_sql_errorcategory.csv
/Users/tianyisun/Desktop/NLQbatches/batch123/correct_batch1_category_Krippendroffis_alpha.csv
/Users/tianyisun/Desktop/NLQbatches/batch123/.DS_Store
/Users/tianyisun/Desktop/NLQbatches/batch123/correct_batch3_category_Krippendroffis_alpha.csv
/Users/tianyisun/Desktop/NLQbatches/batch123/correct_batch1_sql-type_Krippendroffis_alpha.csv
/Users/tianyisun/Desktop/NLQbatches/batch123/correct_batch2_sql-type_Fleiss_kappa.csv
/Users/tianyisun/Desktop/NLQbatches/batch123/correct_batch2_category_Fleiss_kappa.csv
/Users/tianyisun/Desktop/NLQbatches/batch123/correct_batch1_anntask_sql_type.csv
/Users/tianyisun/Desktop/NLQbatches/batch123/revise2_ning_tian.csv
/Users/tianyisun/Desktop/NLQbatches/batch123/correct_batch2_sql-type_Krippendroffis_alpha.csv
/Users/tianyisun/Desktop/NLQbatches/batch123/revise1_ning_tian.csv
/Users/tianyisun/Desktop/NLQbatches/batch123/correct_batch1_sql-category_Fleiss_kappa.csv
/Users/tianyisun/Desktop/NLQbatches/batch123/correct_batch2_category_Krippendroffis_alpha.csv
/Users/tianyisun/Desktop/NLQbatches/batch123/correct_batch1_sql-category_Krippendroffis_alpha.csv
/Users/tianyisun/Desktop/NLQbatches/batch123/correct_batch3_sql-category_Krippendroffis_alpha.csv
/Users/tianyisun/Desktop/NLQbatches/batch123/correct_batch2_sql-category_Krippendroffis_alpha.csv
/Users/tianyisun/Desktop/NLQbatches/batch123/correct_batch2_sql-category_Fleiss_kappa.csv
/Users/tianyisun/Desktop/NLQbatches/batch123/correct_batch3_anntask_sql_errorcategory.csv
/Users/tianyisun/Desktop/NLQbatches/batch123/correct_batch3_category_Fleiss_kappa.csv
/Users/tianyisun/Desktop/NLQbatches/batch123/correct_batch2_anntask_sql_type.csv
/Users/tianyisun/Desktop/NLQbatches/batch123/correct_batch3_sql-type_Fleiss_kappa.csv
/Users/tianyisun/Desktop/NLQbatches/batch123/revise3_ning_tian.csv
/Users/tianyisun/Desktop/NLQbatches/batch123/correct_batch3_sql-category_Fleiss_kappa.csv
/Users/tianyisun/Desktop/NLQbatches/batch123/correct_batch3_anntask_sql_type.csv
/Users/tianyisun/Desktop/NLQbatches/batch123/correct_batch1_category_Fleiss_kappa.csv
/Users/tianyisun/Desktop/NLQbatches/batch123/correct_batch2_anntask_sql_errorcategory.csv
/Users/tianyisun/Desktop/NLQbatches/batch123/correct_batch1_sql-type_Fleiss_kappa.csv

In [50]:
'''Fleiss_kappa for error_category - sql_id'''
errorcategory = pd.read_csv('/Users/tianyisun/Desktop/NLQbatches/batch123/correct_batch1_anntask_sql_errorcategory.csv')
errorcategory =errorcategory.drop(columns=['Unnamed: 0'], axis=1)
errorcategory = errorcategory[['username','sql_id','code']]
print('length: ', len(errorcategory.sql_id.unique()))
'''calculate Fleiss_kappa'''
errorcategory_matrix,errorcategory_id = matrix(errorcategory)
ls = split_matrix(errorcategory_matrix)
ls = [1 if math.isnan(x) else x for x in ls]
catsign= np.sign(ls)
errorcategory_matrix_ave_F_kappa = sum(ls)/len(ls)
errorcategory_id['category_Fleiss_kappa'] = ls
result = pd.DataFrame([[errorcategory_matrix_ave_F_kappa]], columns=['category_Fleiss_kappa'],index = ['average'])
result = errorcategory_id.append(result)
result

length:  44

         category_Fleiss_kappa
2149                  1.000000
532                   1.000000
2094                  1.000000
1125                  1.000000
2294                  1.000000
1274                  1.000000
251                   0.741176
1978                  1.000000
2018                  1.000000
1331                  0.614035
1139                  1.000000
2179                  1.000000
2153                  1.000000
2168                  0.790476
2000                  0.266667
1961                  1.000000
1578                  1.000000
1585                  1.000000
1671                  1.000000
1704                  1.000000
2373                  1.000000
798                   1.000000
1131                  1.000000
2374                  1.000000
1151                  1.000000
2051                  1.000000
1880                  1.000000
2069                  0.741176
2367                 -0.100000
2312                  1.000000
361                   1.000000
2037                  1.000000
1841                  1.000000
2078                  0.741176
2151                  1.000000
2025                  0.741176
2070                  1.000000
1804                  1.000000
1747                  0.388889
1673                  1.000000
2310                  0.388889
2061                  1.000000
478                   1.000000
1189                  1.000000
average               0.893492

In [46]:
#errorcategory_matrix.to_csv('check_fleiss_kappa.csv', index = True)

In [57]:
#result.to_csv('batch123/correct_batch1_sql-category_Fleiss_kappa.csv')

In [58]:
### '''Fleiss_kappa for error_type - sql_id'''
errortype = pd.read_csv('/Users/tianyisun/Desktop/NLQbatches/batch123/correct_batch1_anntask_sql_type.csv')
errortype =errortype.drop(columns=['Unnamed: 0'], axis=1)
errortype = errortype[['username','sql_id','code']]
print('length: ', len(errortype.sql_id.unique()))
'''calculate Fleiss_kappa'''
errortype_matrix,errortype_id = matrix(errortype)
ls = split_matrix(errortype_matrix)
ls = [1 if math.isnan(x) else x for x in ls]
#typesign = np.sign(ls)
#for index in range(0,len(ls)): 
#    if typesign[index]!=catsign[index]:
#        ls[index] = -ls[index]
#    if 0< ls[index]<0.1:
#        ls[index] =ls[index]*10
errortype_matrix_ave_F_kappa = sum(ls)/len(ls)
errortype_id['type_Fleiss_kappa'] = ls
result2 = pd.DataFrame([[errortype_matrix_ave_F_kappa]], columns=['type_Fleiss_kappa'],index = ['average'])
result2 = errortype_id.append(result2)
print(len(result2))
result2

length:  44
45

         type_Fleiss_kappa
2149              1.000000
532               0.341176
2094              1.000000
1125              0.647799
2294              0.461538
1274              1.000000
251               0.647799
1978              1.000000
2018              1.000000
1331              0.780392
1139              1.000000
2179              1.000000
2153              1.000000
2168              0.780392
2000              0.510204
1961             -0.037037
1578              1.000000
1585              1.000000
1671              1.000000
1704              1.000000
2373              1.000000
798               1.000000
1131              1.000000
2374              1.000000
1151              1.000000
2051              1.000000
1880              1.000000
2069              0.647799
2367             -0.037037
2312              1.000000
361               1.000000
2037              1.000000
1841             -0.037037
2078              0.647799
2151              1.000000
2025              0.780392
2070              1.000000
1804             -0.037037
1747             -0.037037
1673              1.000000
2310             -0.037037
2061              1.000000
478               1.000000
1189              1.000000
average           0.773252

In [59]:
#result2.to_csv('batch123/correct_batch1_sql-type_Fleiss_kappa.csv')

In [76]:
disagreement_result

         Fleiss_kappa
A            0.932876
B            0.950198
L            0.951515
C            0.832381
K            0.725000
D            1.000000
F            0.729231
N            0.725000
O            1.000000
P            1.000000
E            0.823411
average      0.879056

In [84]:
A_ = len(disagreement[disagreement['code'] == 'A'])/len(disagreement['code'])
B_ = len(disagreement[disagreement['code'] == 'B'])/len(disagreement['code'])
L_ = len(disagreement[disagreement['code'] == 'L'])/len(disagreement['code'])
C_ = len(disagreement[disagreement['code'] == 'C'])/len(disagreement['code'])
K_ = len(disagreement[disagreement['code'] == 'K'])/len(disagreement['code'])
D_ = len(disagreement[disagreement['code'] == 'D'])/len(disagreement['code'])
F_ = len(disagreement[disagreement['code'] == 'F'])/len(disagreement['code'])
N_ = len(disagreement[disagreement['code'] == 'N'])/len(disagreement['code'])
O_ = len(disagreement[disagreement['code'] == 'O'])/len(disagreement['code'])
P_ = len(disagreement[disagreement['code'] == 'P'])/len(disagreement['code'])
E_ = len(disagreement[disagreement['code'] == 'E'])/len(disagreement['code'])
quan = [A_,B_, L_, C_, K_, D_, F_, N_, O_, P_, E_, 0.879056]

In [60]:
'''Fleiss_kappa for error_category '''
disagreement = errorcategory[['username','code','sql_id']]

'''calculate Fleiss_kappa'''
disagreement_matrix,id = matrix(disagreement)
ls = split_matrix(disagreement_matrix)
ls = [1 if math.isnan(x) else x for x in ls]
disagreement_matrix_ave_F_kappa = sum(ls)/len(ls)
id['Fleiss_kappa'] = ls
disagreement_result = pd.DataFrame([[disagreement_matrix_ave_F_kappa]], columns=['Fleiss_kappa'],index = ['average'])
#print(len(disagreement_result))
disagreement_result = id.append(disagreement_result)
disagreement_result

         Fleiss_kappa
A            0.932876
B            0.950198
L            0.951515
C            0.832381
K            0.725000
D            1.000000
F            0.729231
N            0.725000
O            1.000000
P            1.000000
E            0.823411
average      0.879056

In [87]:
quan

[0.1043956043956044,
 0.17032967032967034,
 0.1813186813186813,
 0.13736263736263737,
 0.04395604395604396,
 0.0989010989010989,
 0.07142857142857142,
 0.04395604395604396,
 0.01098901098901099,
 0.01098901098901099,
 0.12637362637362637,
 0.879056]

In [88]:
list(disagreement_result['Fleiss_kappa'].T)*quan

[0.9328756674294433,
 0.9501980758347482,
 0.9515151515151515,
 0.8323809523809522,
 0.7250000000000004,
 1.0,
 0.7292307692307689,
 0.7250000000000004,
 1.0,
 1.0,
 0.8234113712374581,
 0.8790556352389568]

In [61]:
#disagreement_result.to_csv('batch123/correct_batch1_category_Fleiss_kappa.csv')

---
---